import type { Metadata } from 'next'
import { Open_Sans, Poppins } from 'next/font/google'
import  styles from'./page.module.css'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import NavBar from './components/nav/NavBar'

const OpenSans = Open_Sans({ 
  subsets: ['latin'] 
  ,weight:[ "300" , '400',"500", "600", "700", "800"], 
  style: ['normal', 'italic'],
  display:'swap'

})
const PoppinsFont = Poppins({
  subsets: ['latin'] 
  ,weight:[ "100", "200" ,"300", '400',"500", "600", "700", "800","900"], 
  style: ['normal', 'italic'],
  display:'swap'

})

export const metadata: Metadata = {
  title: 'Digital Web Solution',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AppRouterCacheProvider options={{ enableCssLayer: true }}> 
        <body className={`${PoppinsFont.className} ${styles.main}`}>
          <NavBar/>
          {children}
        </body>
      </AppRouterCacheProvider>
    </html>
  )
}
